### PR TITLE
Upgrade Nightmare to latest git

### PR DESCRIPTION
**Pull request by DaQuirm**
The latest git version has this fix: 
https://github.com/segmentio/nightmare/pull/487
which makes running Gunslinger tests much more comfortable (no need to kill zombified Sandbox Electron) :cat:

### CODE REVIEW

**Comment by R1ZZU** [comment]
maybe add commit sha?

**Comment by R1ZZU** [comment]
also as nightmare is github hosted, we don't need full git urls, `segmentio/nightmare#commit-sha` is enough

**Comment by DaQuirm** [comment]
Wow, let me try that later.
Thanks for the hint! :cat:

**Comment by DaQuirm** [comment]
On a side note, github has comment reactions now??? :open_mouth:

**Comment by R1ZZU** [comment]
Dear Github, we need commit reactions! 😹

**Pull request merged**
